### ISSUE TITLE
Java.io.IOException & Error Downloading

### ISSUE THREAD

**Issue by trawinlegacy** [Seeed-Studio/stm32f4ArduinoCore#9]
I have been using a **WIO LTE Cat 1** board for little over a month now and one day while doing tests I tried running a script that had been working minutes previously and gave me the following error:
**java.io.IOException: Cannot run program "{runtime.tools.stm32 dfu upload_tool.path}/win/dfu upload.bat": CreateProcess error=2**

I tried deleting the App Data Roaming and Local Arduino15 folders and reinstalling the Arduino IDE but now get the following error:
**Error downloading https://raw.githubusercontent.com/Seeed-Studio/Seeed_Platform/master/package_seeeduino_boards_index.json**

**Comment by martenbiehl** [comment]
Running into the same issue. The file has been renamed https://github.com/Seeed-Studio/Seeed_Platform/issues/21
The dfu-util error is still there though.

**Comment by Pillar1989** [comment]
https://github.com/Seeed-Studio/stm32f4ArduinoCore/commit/aca4b28bf0099846c346b742bbd05dfb19da9f03

**Comment by trawinlegacy** [comment]
The board package can download and I can install the Seeed STM32F4 driver however I get the following error when a script is ran:
**exec: "/bin/arm-none-eabi-g++": file does not exist
Error compiling for board Wio Tracker LTE.**

**Comment by martenbiehl** [comment]
These are two issues.

1. The board definitions have been renamed (the commit you reference is the solution)
2. The flash script cannot find the dfu tool. Neither on macOS nor on windows.

Any guidance on how to solve the latter?

Could you reopen this issue, please?

<img width="1153" alt="Screenshot 2020-09-29 at 10 49 04" src="https://user-images.githubusercontent.com/296533/94535235-a045f080-0241-11eb-8e73-a65283f0bc21.png">


```
Arduino: 1.8.12 (Mac OS X), Board: "Wio Tracker LTE"

Sketch uses 20368 bytes (1%) of program storage space. Maximum is 1048576 bytes.
Global variables use 24304 bytes of dynamic memory.
java.io.IOException: Cannot run program "{runtime.tools.stm32_dfu_upload_tool.path}/macosx/dfu_upload": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:11)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.SerialUploader.runCommand(SerialUploader.java:383)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:197)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2047)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 11 more
An error occurred while uploading the sketch

```

**Comment by jiacheng-lu** [comment]
Please try again, this stm32_dfu_upload_tool problem has been fixed.

**Comment by martenbiehl** [comment]
Can confirm. This is fixed now.

Thanks a lot for the speedy fix!
